POST http://localhost:8080/api/users/62a0db99171435f70764f24e/reset-password
Content-Type: application/json

{
  "token": "d.eyJ1c2VySWQiOiI2MmEwZGI5OTE3MTQzNWY3MDc2NGYyNGUiLCJpYXQiOjE2NTQ3MTIxOTYsImV4cCI6MTY1NDcxMjc5Nn0.9Lxl8b4adhUAPfYWX2DSdpB6jUzfFZRpkJm3LtwamMs",
  "newPassword": "123456"
}