export const registerFormInputs = {
  firstname: {
    id: "firstname_input_id",
    name: "firstname",
    label: "",
    role: "firstname-input",
    ariaLabel: "firstname-input",
    placeholder: "Your first name",
    type: "text",
    autoComplete: "off",
  },
  lastname: {
    id: "lastname_input_id",
    name: "lastname",
    label: "",
    role: "lastname-input",
    ariaLabel: "lastname-input",
    placeholder: "Your last name",
    type: "text",
    autoComplete: "off",
  },
  email: {
    id: "email_input_id",
    name: "email",
    label: "",
    role: "email-input",
    ariaLabel: "email-input",
    placeholder: "Your email address",
    type: "email",
    autoComplete: "off",
  },
  password: {
    id: "password_input_id",
    name: "password",
    label: "",
    role: "password-input",
    ariaLabel: "password-input",
    placeholder: "Your password",
    type: {
      hidden: "password",
      show: "text",
    },
    autoComplete: "off",
  },
  confirmPassword: {
    id: "confirmPassword_input_id",
    name: "confirmPassword",
    label: "",
    role: "confirmPassword-input",
    ariaLabel: "confirmPassword-input",
    placeholder: "Confirm your password",
    type: {
      hidden: "password",
      show: "text",
    },
    autoComplete: "off",
  },
}
