export const inputs = {
  email: {
    id: "email_input_id",
    name: "email",
    label: "",
    role: "email-input",
    ariaLabel: "email-input",
    placeholder: "Your email address",
    type: "email",
    autoComplete: "off",
  },
  password: {
    id: "password_input_id",
    name: "password",
    label: "",
    role: "password-input",
    ariaLabel: "password-input",
    placeholder: "Your password",
    type: {
      hidden: "password",
      show: "text",
    },
    autoComplete: "off",
  },
  firstname: {
    id: "firstname_input_id",
    name: "firstname",
    label: "",
    role: "firstname-input",
    ariaLabel: "firstname-input",
    placeholder: "Your first name",
    type: "text",
    autoComplete: "off",
  },
  lastname: {
    id: "lastname_input_id",
    name: "lastname",
    label: "",
    role: "lastname-input",
    ariaLabel: "lastname-input",
    placeholder: "Your last name",
    type: "text",
    autoComplete: "off",
  },
  username: {
    id: "username_input_id",
    name: "username",
    label: "",
    role: "username-input",
    ariaLabel: "username-input",
    placeholder: "Your username",
    type: "text",
    autoComplete: "off",
  },
  description: {
    id: "description_input_id",
    name: "description",
    label: "",
    role: "description-input",
    ariaLabel: "description-input",
    placeholder: "Your description",
    type: "text",
    autoComplete: "off",
  },
}
